// src/constants/topicNames.js
// Maps attempt_topics.id → human-readable name for AI prompts.
// IDs must match the seeded attempt_topics reference table.
// Never send raw topic IDs to Haiku or Sonnet — always resolve through this map.

export const TOPIC_NAMES = {
  // Grammar (1–25)
  1:  "Nominative case",
  2:  "Accusative case",
  3:  "Accusative (animate)",
  4:  "Genitive case",
  5:  "Genitive plural",
  6:  "Dative case",
  7:  "Instrumental case",
  8:  "Prepositional case",
  9:  "Verb aspect",
  10: "Verb conjugation",
  11: "Verbs of motion",
  12: "Adjective agreement",
  13: "Short adjectives",
  14: "Pronouns",
  15: "Numbers",
  16: "Word order",
  17: "Negation",
  18: "Comparative",
  19: "Superlative",
  20: "Reflexive verbs",
  21: "Participles",
  22: "Gerunds",
  23: "Conditional",
  24: "Subjunctive",
  25: "Prepositions",
  // Vocabulary (50–55)
  50: "Vocabulary (general)",
  51: "Vocabulary (verbs)",
  52: "Vocabulary (nouns)",
  53: "Vocabulary (adjectives)",
  54: "Vocabulary (adverbs)",
  55: "Vocabulary (phrases)",
  // Reading (80–86)
  80: "Reading (detail recall)",
  81: "Reading (inference)",
  82: "Reading (vocabulary)",
  83: "Reading (true/false)",
  84: "Reading (sequence)",
  85: "Reading (free response)",
  86: "Reading (grammar spotlight)",
  // Song (90–93)
  90: "Song (translation)",
  91: "Song (meaning)",
  92: "Song (cloze)",
  93: "Song (recall)",
};

// Abbreviated names for CSV columns (saves tokens)
// Used in the AI prompt CSVs — same ID mapping, shorter strings
export const TOPIC_NAMES_SHORT = {
  1:  "Nominative",
  2:  "Accusative",
  3:  "Accusative-animate",
  4:  "Genitive",
  5:  "Genitive-pl",
  6:  "Dative",
  7:  "Instrumental",
  8:  "Prepositional",
  9:  "Verb-aspect",
  10: "Verb-conj",
  11: "Verb-motion",
  12: "Adj-agreement",
  13: "Short-adj",
  14: "Pronouns",
  15: "Numbers",
  16: "Word-order",
  17: "Negation",
  18: "Comparative",
  19: "Superlative",
  20: "Reflexive",
  21: "Participles",
  22: "Gerunds",
  23: "Conditional",
  24: "Subjunctive",
  25: "Prepositions",
  50: "Vocab-gen",
  51: "Vocab-verbs",
  52: "Vocab-nouns",
  53: "Vocab-adj",
  54: "Vocab-adv",
  55: "Vocab-phrases",
  80: "Read-detail",
  81: "Read-infer",
  82: "Read-vocab",
  83: "Read-tf",
  84: "Read-seq",
  85: "Read-free",
  86: "Read-grammar",
  90: "Song-trans",
  91: "Song-meaning",
  92: "Song-cloze",
  93: "Song-recall",
};